//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceYourCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int B_id { get; set; }
        public Nullable<int> St_id { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> E_Time { get; set; }
        public Nullable<System.DateTime> S_Time { get; set; }
        public Nullable<bool> complete { get; set; }
        public Nullable<bool> B_type { get; set; }
        public Nullable<int> S_id { get; set; }
    }
}
