//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceYourCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int Rem_id { get; set; }
        public Nullable<int> B_id { get; set; }
        public Nullable<System.DateTime> Rem_date { get; set; }
    }
}
