//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceYourCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Sr_id { get; set; }
        public Nullable<int> N_price { get; set; }
        public string S_name { get; set; }
        public Nullable<int> St_id { get; set; }
        public Nullable<int> S_time { get; set; }
        public Nullable<int> V_price { get; set; }
    }
}
