//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceYourCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        public int Slot_id { get; set; }
        public string day { get; set; }
        public Nullable<System.DateTime> Open_time { get; set; }
        public Nullable<System.DateTime> Closed_time { get; set; }
        public Nullable<int> St_id { get; set; }
    }
}
