//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceYourCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public int St_id { get; set; }
        public string St_name { get; set; }
        public Nullable<int> S_id { get; set; }
        public string Address { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lng { get; set; }
    }
}
