//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceYourCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int S_id { get; set; }
        public string Email { get; set; }
        public string User_name { get; set; }
        public string Password { get; set; }
        public string Mobile_Number { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsUser { get; set; }
    }
}
